[package]
name = "procon-client"
version = "0.1.0"
edition = "2024"

[dependencies]
chaser = {path = "../chaser", default-features = false}
fastrand = "2.3.0"
pathfinding = "4.14.0"

[features]
default = ["ui", "fow"]
ui = ["chaser/ui"]
fow = ["chaser/fog_of_war"]
