[package]
name = "procon-client"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
chaser = {path = "../chaser"}
fastrand = "2.3.0"
pathfinding = "4.14.0"

[features]
ui = ["chaser/ui"]
fow = ["chaser/fog_of_war"]


